server.port=8082
# Database Configuration (Uses H2 In-Memory for now)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Allow the app to run even if some security beans are still loading
spring.main.allow-bean-definition-overriding=true